library(shiny)
library(shinydashboard)
library(shinyjs)
library(shinyWidgets)
library(wordcloud)
library(wordcloud2)
library(RColorBrewer)
library(plotly)
library(shinythemes)
library(DT)
library(tm)
library(SnowballC)
library(dplyr)
library(ggplot2)

source("./functions/get_clean_text.R", local = TRUE)
source("./functions/get_term_document_matrix.R", local = TRUE)